config/routes.rb
Rails.application.routes.draw do
  resources :discount_activities
  resources :publication_activities
  resources :activity_types
  resources :discounts
  resources :publications

end

app/models/publication_activity.rb
class PublicationActivity < ActiveRecord::Base
    belongs_to:publication
    belongs_to:activity_type
end

app/controllers/publication_activities_controller.rb
class PublicationActivitiesController < ApplicationController
  before_action :set_publication_activity, only: [:show, :edit, :update, :destroy]

  # GET /publication_activities
  # GET /publication_activities.json
  def index
    @publication_activities = PublicationActivity.all
  end

  # GET /publication_activities/1
  # GET /publication_activities/1.json
  def show
  end

  # GET /publication_activities/new
  def new
    @publication_activity = PublicationActivity.new
  end

  # GET /publication_activities/1/edit
  def edit
  end

  # POST /publication_activities
  # POST /publication_activities.json
  def create
    @publication_activity = PublicationActivity.new(publication_activity_params)

    respond_to do |format|
      if @publication_activity.save
        format.html { redirect_to @publication_activity, notice: 'Publication activity was successfully created.' }
        format.json { render :show, status: :created, location: @publication_activity }
      else
        format.html { render :new }
        format.json { render json: @publication_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publication_activities/1
  # PATCH/PUT /publication_activities/1.json
  def update
    respond_to do |format|
      if @publication_activity.update(publication_activity_params)
        format.html { redirect_to @publication_activity, notice: 'Publication activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication_activity }
      else
        format.html { render :edit }
        format.json { render json: @publication_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publication_activities/1
  # DELETE /publication_activities/1.json
  def destroy
    @publication_activity.destroy
    respond_to do |format|
      format.html { redirect_to publication_activities_url, notice: 'Publication activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication_activity
      @publication_activity = PublicationActivity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_activity_params
      params.require(:publication_activity).permit(:publication_id, :activity_type_id, :date, :time)
    end
end

app/helpers/publication_activities_helper.rb
module PublicationActivitiesHelper
end

app/views/publication_activities/_form.html.erb
<%= form_for(@publication_activity) do |f| %>
  <% if @publication_activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication_activity.errors.count, "error") %> prohibited this publication_activity from being saved:</h2>

      <ul>
      <% @publication_activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :publication_id %><br>
    <%= f.number_field :publication_id %>
  </div>
  <div class="field">
    <%= f.label :activity_type_id %><br>
    <%= f.number_field :activity_type_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publication_activities/edit.html.erb
<h1>Editing Publication Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication_activity %> |
<%= link_to 'Back', publication_activities_path %>

app/views/publication_activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Publication Activities</h1>

<table>
  <thead>
    <tr>
      <th>Publication</th>
      <th>Activity type</th>
      <th>Date</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publication_activities.each do |publication_activity| %>
      <tr>
        <td><%= publication_activity.publication_id %></td>
        <td><%= publication_activity.activity_type.name %></td>
        <td><%= publication_activity.date %></td>
        <td><%= publication_activity.time %></td>
        <td><%= link_to 'Show', publication_activity %></td>
        <td><%= link_to 'Edit', edit_publication_activity_path(publication_activity) %></td>
        <td><%= link_to 'Destroy', publication_activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publication activity', new_publication_activity_path %>

app/views/publication_activities/new.html.erb
<h1>New Publication Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', publication_activities_path %>

app/views/publication_activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Publication:</strong>
  <%= @publication_activity.publication_id %>
</p>

<p>
  <strong>Activity type:</strong>
  <%= @publication_activity.activity_type_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @publication_activity.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @publication_activity.time %>
</p>

<%= link_to 'Edit', edit_publication_activity_path(@publication_activity) %> |
<%= link_to 'Back', publication_activities_path %>